import React from 'react';
import { H1, H2, H3 } from '../components/typography/headers';
import Paragraph from '../components/typography/Paragraph';
import Body from '../components/typography/TypographyBody';

export default () =>
  <Body>
    <H1>Privacy Policy</H1>
    <Paragraph>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mattis pellentesque id nibh tortor id aliquet lectus. Quisque non tellus orci ac auctor. Est lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque. Vel eros donec ac odio tempor. Malesuada bibendum arcu vitae elementum curabitur. Ut sem viverra aliquet eget sit amet tellus. Ut venenatis tellus in metus vulputate eu scelerisque felis. Tempus quam pellentesque nec nam aliquam sem et tortor. Vivamus at augue eget arcu dictum varius. Massa massa ultricies mi quis hendrerit dolor magna. Amet luctus venenatis lectus magna fringilla. Arcu dui vivamus arcu felis bibendum ut tristique et egestas.</Paragraph>
    <H2>Eget Nunc Scelerisque</H2>
    <Paragraph>Vestibulum morbi blandit cursus risus at ultrices mi tempus imperdiet. Eget nunc scelerisque viverra mauris in aliquam sem. Amet luctus venenatis lectus magna fringilla urna. Augue lacus viverra vitae congue eu consequat ac felis.</Paragraph>
    <Paragraph>Vulputate odio ut enim blandit volutpat maecenas volutpat blandit aliquam. Facilisis volutpat est velit egestas dui. Ornare quam viverra orci sagittis eu volutpat. Habitasse platea dictumst vestibulum rhoncus est pellentesque. Diam sit amet nisl suscipit adipiscing bibendum est ultricies integer. Ut lectus arcu bibendum at varius. Velit dignissim sodales ut eu sem integer vitae justo. Velit sed ullamcorper morbi tincidunt ornare massa eget. Tempor id eu nisl nunc mi. Enim ut sem viverra aliquet eget. Sem nulla pharetra diam sit amet nisl suscipit adipiscing. Laoreet id donec ultrices tincidunt. Duis convallis convallis tellus id interdum velit laoreet. Tempor orci dapibus ultrices in.</Paragraph>
    <H2>Metus Aliquam Eleifend</H2>
    <Paragraph>At erat pellentesque adipiscing commodo elit. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. In fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Molestie a iaculis at erat pellentesque adipiscing commodo. Nulla facilisi nullam vehicula ipsum a arcu cursus. Urna nec tincidunt praesent semper feugiat. Purus in mollis nunc sed id semper risus in. Volutpat blandit aliquam etiam erat velit scelerisque in. Sed odio morbi quis commodo odio aenean. Morbi tincidunt ornare massa eget egestas purus.</Paragraph>
    <Paragraph>Sit amet volutpat consequat mauris nunc congue. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum arcu. Venenatis cras sed felis eget velit aliquet sagittis id. Sed odio morbi quis commodo odio. Quis imperdiet massa tincidunt nunc. Urna neque viverra justo nec ultrices dui sapien eget mi. At varius vel pharetra vel turpis nunc eget lorem dolor. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae congue. Nullam eget felis eget nunc. Urna id volutpat lacus laoreet non curabitur gravida.</Paragraph>
    <Paragraph>Habitasse platea dictumst vestibulum rhoncus est pellentesque. Diam sit amet nisl suscipit adipiscing bibendum est ultricies integer. Ut lectus arcu bibendum at varius. Velit dignissim sodales ut eu sem integer vitae justo. Velit sed ullamcorper morbi tincidunt ornare massa eget. Leo urna molestie at elementum eu facilisis sed. Tempor id eu nisl nunc mi. Enim ut sem viverra aliquet eget. Sem nulla pharetra diam sit amet nisl suscipit adipiscing. Laoreet id donec ultrices tincidunt. Duis convallis convallis tellus id interdum velit laoreet. Tempor orci dapibus ultrices in.</Paragraph>
    <Paragraph>Tristique senectus et netus et malesuada fames ac turpis. At elementum eu facilisis sed. Dictum varius duis at consectetur lorem. Nisl suscipit adipiscing bibendum est ultricies integer quis auctor elit. Amet tellus cras adipiscing enim eu turpis. Nunc consequat interdum varius sit. Lorem donec massa sapien faucibus et molestie ac feugiat. Sed cras ornare arcu dui vivamus. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Justo laoreet sit amet cursus sit amet dictum. Vel pretium lectus quam id. Non blandit massa enim nec dui nunc. Leo urna molestie at elementum eu facilisis sed. Eget nunc lobortis mattis aliquam faucibus purus in massa. At ultrices mi tempus imperdiet nulla malesuada pellentesque.</Paragraph>
    <H2>Ornare Quam Viverra Orci</H2>
    <Paragraph>At erat pellentesque adipiscing commodo elit. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. In fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Molestie a iaculis at erat pellentesque adipiscing commodo. Nulla facilisi nullam vehicula ipsum a arcu cursus. Urna nec tincidunt praesent semper feugiat. Purus in mollis nunc sed id semper risus in. Volutpat blandit aliquam etiam erat velit scelerisque in. Sed odio morbi quis commodo odio aenean. Morbi tincidunt ornare massa eget egestas purus.</Paragraph>
    <H3>Blandit Aliquam</H3>
    <Paragraph>Vestibulum morbi blandit cursus risus at ultrices mi tempus imperdiet. Eget nunc scelerisque viverra mauris in aliquam sem. Amet luctus venenatis lectus magna fringilla urna. Augue lacus viverra vitae congue eu consequat ac felis.</Paragraph>
    <H3>Metus Aliquam</H3>
    <Paragraph>Vulputate odio ut enim blandit volutpat maecenas volutpat blandit aliquam. Facilisis volutpat est velit egestas dui. Ornare quam viverra orci sagittis eu volutpat. Habitasse platea dictumst vestibulum rhoncus est pellentesque. Diam sit amet nisl suscipit adipiscing bibendum est ultricies integer. Ut lectus arcu bibendum at varius. Velit dignissim sodales ut eu sem integer vitae justo. Velit sed ullamcorper morbi tincidunt ornare massa eget. Tempor id eu nisl nunc mi. Enim ut sem viverra aliquet eget. Sem nulla pharetra diam sit amet nisl suscipit adipiscing. Laoreet id donec ultrices tincidunt. Duis convallis convallis tellus id interdum velit laoreet. Tempor orci dapibus ultrices in.</Paragraph>
    <Paragraph>At erat pellentesque adipiscing commodo elit. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. In fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Molestie a iaculis at erat pellentesque adipiscing commodo. Nulla facilisi nullam vehicula ipsum a arcu cursus. Urna nec tincidunt praesent semper feugiat. Purus in mollis nunc sed id semper risus in. Volutpat blandit aliquam etiam erat velit scelerisque in. Sed odio morbi quis commodo odio aenean. Morbi tincidunt ornare massa eget egestas purus.</Paragraph>
    <H2>Eget Nunc Scelerisque</H2>
    <Paragraph>Vestibulum morbi blandit cursus risus at ultrices mi tempus imperdiet. Eget nunc scelerisque viverra mauris in aliquam sem. Amet luctus venenatis lectus magna fringilla urna. Augue lacus viverra vitae congue eu consequat ac felis.</Paragraph>
    <Paragraph>Vulputate odio ut enim blandit volutpat maecenas volutpat blandit aliquam. Facilisis volutpat est velit egestas dui. Ornare quam viverra orci sagittis eu volutpat. Habitasse platea dictumst vestibulum rhoncus est pellentesque. Diam sit amet nisl suscipit adipiscing bibendum est ultricies integer. Ut lectus arcu bibendum at varius. Velit dignissim sodales ut eu sem integer vitae justo. Velit sed ullamcorper morbi tincidunt ornare massa eget. Tempor id eu nisl nunc mi. Enim ut sem viverra aliquet eget. Sem nulla pharetra diam sit amet nisl suscipit adipiscing. Laoreet id donec ultrices tincidunt. Duis convallis convallis tellus id interdum velit laoreet. Tempor orci dapibus ultrices in.</Paragraph>
  </Body>
